<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
// this file was crated for shop.store route
// this file locates in app/Http/Request
// this file was generated by running
// php artisan make:request ShopStoreRequest
class ShopStoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        $user = auth()->user();

        // User must have admin role (can have multiple shops)
        return $user && $user->hasRole('admin');
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'name' => 'required|string|max:50|min:3',
            'profile_pic' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ];
    }
}
